### ISSUE TITLE
it doesnt work

### ISSUE THREAD

**Issue by Directorhappy** [yiruzu/esx-getSharedObject-fix#2]
it stops all other esx stuff from working

**Comment by yiruzu** [comment]
If you did it the right way you shouldn't have any problems.

**Comment by Directorhappy** [comment]
I did it the way you showed

Sent from my T-Mobile 5G Device
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by yiruzu** [comment]
```lua
AddEventHandler("esx:getSharedObject", function(cb)
    cb(ESX) 
end)
```
You can also only use this. (replace it in both common lua's at the top.

**Comment by Directorhappy** [comment]
I will try it in the next few days and let you know

Sent from my T-Mobile 5G Device
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Directorhappy** [comment]
please add me on discord this is still not working
DirectorHappy#0082
