### ISSUE TITLE
Not working for ESX Legacy 1.10.2

### ISSUE THREAD

**Issue by KfzMatze45** [yiruzu/esx-getSharedObject-fix#7]
I was advised to install it, but it didn't work

**Comment by yiruzu** [comment]
What was your initial problem?

**Comment by KfzMatze45** [comment]
It didn't help. After the installation, old ESX queries didn't work. When testing with version 1.10.1 it worked again. Apparently something must be different in 1.10.2 so it no longer works

**Comment by yiruzu** [comment]
It still works for me, can you show me how you "installed" it?

**Comment by KfzMatze45** [comment]
Well es_extended 1.10.2 on the test server and in the client and server that replaces them. An old system of es_extended v1 was taken and boom ESX error under F8

https://i.imglol.de/Unbenannt4cbpr3z5.png

**Comment by KfzMatze45** [comment]
I then did the same thing again with es_extended 1.10.1 and there were no errors and the script ran

**Comment by stxrlite** [comment]
did you ever get this resolved

**Comment by yiruzu** [comment]
Does it still not work?
