### ISSUE TITLE
installation instructions update request

### ISSUE THREAD

**Issue by duhimhype** [yiruzu/esx-getSharedObject-fix#8]
as the title says can you explain more in depth on the main download page on what line we need to replace in common.lua for each?

**Comment by yiruzu** [comment]
Replace those lines:

![image_2023-12-26_131401426](https://github.com/yiruzu/esx-getSharedObject-fix/assets/94981325/85ecccad-80b1-42e2-86d0-4ea490455b3d)
![image_2023-12-26_131433717](https://github.com/yiruzu/esx-getSharedObject-fix/assets/94981325/30eecf0b-e255-4b20-83c9-7d35385910d3)

**Comment by duhimhype** [comment]
your amazing for the fast response thank you very much
