### ISSUE TITLE
Doesnt work with any esx version..

### ISSUE THREAD

**Issue by free4allxd** [yiruzu/esx-getSharedObject-fix#9]
i dont know what im doeing from, for me its not working with any esx version. 

At first i replaced this code in es_extended/ (1.10.5)client/common.lua 

exports("getSharedObject", function()
    return ESX
end)

AddEventHandler("esx:getSharedObject", function()
    local Invoke = GetInvokingResource()
    print(("[^1ERROR^7] Resource ^5%s^7 Used the ^5getSharedObject^7 Event, this event ^1no longer exists!^7 Visit https://documentation.esx-framework.org/tutorials/tutorials-esx/sharedevent for how to fix!"):format(Invoke))
end)

To: 
AddEventHandler("esx:getSharedObject", function(cb)
    cb(ESX) 
end)

And then in server/common.lua

from; AddEventHandler("esx:getSharedObject", function()
    local Invoke = GetInvokingResource()
    print(("[^1ERROR^7] Resource ^5%s^7 Used the ^5getSharedObject^7 Event, this event ^1no longer exists!^7 Visit https://documentation.esx-framework.org/tutorials/tutorials-esx/sharedevent for how to fix!"):format(Invoke))
end)

exports("getSharedObject", function()
    return ESX
end)

To:
AddEventHandler("esx:getSharedObject", function(cb)
    cb(ESX) 
end)

And thats not working, still getting all the errors. I really need this as some of my "old" scripts dont work with the new implementation. A few one work with the new ESX = exports["es_extended"]:getSharedObject() but sadly some do not.
What am i doeing wrong?

**Comment by yiruzu** [comment]
Just replace the Event Handler not the export
